const Map<String, dynamic> appLanguageLabelKeys = {
  "somethingMSg": "Something went wrong. Please try again after some time",
  "bookmarkLbl": "Bookmarks",
  "loginLbl": "Login",
  "welTitle1": "Your Gateway to Scholarly Knowledge",
  "welTitle2": "Share Knowledge, Spark",
  "welTitle3": "Explore Fascinating Topics",
  "welDes1": "Discover curated educational content across diverse fields. From law to environment and beyond, Starke caters to your passions.",
  "welDes2": "Save and spread knowledge effortlessly with Starke. Bookmark your favorites and share them with ease to inspire others.",
  "welDes3": "Discover expertly curated topics in every category. From legal landmarks to climate research, Starke offers rich content for your exploration.",
  "nameLbl": "Name",
  "emailLbl": "Email",
  "enterEmailLbl": "Enter Your Email Address",
  "passLbl": "Password",
  "confpassLbl": "Confirm Password",
  "priPolicy": "Privacy Policy",
  "andLbl": " and ",
  "termLbl": "Terms of Service",
  "forgotPassLbl": "Forgot Password?",
  "internetmsg": "Internet Connection not available",
  "loginMsg": "Login Successfully",
  "loginNowLbl": "Login Now",
  "logoutLbl": "Logout",
  "cancelBtn": "Cancel",
  "noNews": "News Not Available",
  "exitWR": "Double tap back button to exit",
  "shareLbl": "Share",
  "deactiveMsg": "You are deactivated by admin",
  "bookmarkNotAvail": "Bookmarks Not Available",
  "notiNotAvail": "Notifications Not Available",
  "notificationLbl": "Notifications",
  "notificationPreferences": "Notification Preferences",
  "notificationPreferenceTitle": "Notification Preference",
  "commentReplyNotiTitle": "Comment reply notification",
  "commentReplyNotiDesc": "Get notified when someone replies to your comment.",
  "newsNotiTitle": "News notification",
  "newsNotiDesc": "Stay informed with the latest local and global stories.",
  "promotionalNotiTitle": "Promotional notification",
  "promotionalNotiDesc":
      "Receive updates about special offers, features, and announcements.",
  "podcastNotiTitle": "Podcast notification",
  "podcastNotiDesc": "Listen to in-depth discussions and daily news summaries.",
  "marketAlertNotiTitle": "Market alert notification",
  "marketAlertNotiDesc":
      "Get timely notifications for important news and emergency updates.",
  "logoutTxt": "Are you sure you want to Logout?",
  "yesLbl": "Yes",
  "noLbl": "No",
  "frgtPassHead": "Enter the email address associated with your account",
  "forgotPassSub": "We will email you a link to reset your password",
  "submitBtn": "Submit",
  "verifyEmailMsg": "Please first verify your email address!!!",
  "passReset": "Password reset link has been sent to your mail",
  "profileUpdateMsg": "Profile Data Updated Successfully",
  "bookmarkLogin": "Please Login to Access Your Bookmarks !!",
  "preferenceSave": "Your preference saved!!",
  "managePreferences": "Manage Preferences",
  "loginReqMsg": "Login Required...",
  "firstFillData": "Please First Fill Data...!",
  "deleteTxt": "Delete",
  "reportTxt": "Report",
  "reportComment": "Report Comment",
  "reportHint": "eg. This is fake",
  "deleteComment": "Delete Comment",
  "deleteCommentMsg": "Are you sure you want to Delete?",
  "yesDelete": "Yes, Delete",
  "nameRequired": "Name is Required",
  "nameLength": "Name should be atleast 2 character long",
  "emailRequired": "email address is Required",
  "emailValid": "Please enter a valid email Address!",
  "pwdRequired": "Password is Required",
  "confPassRequired": "Confirm Password is Required",
  "confPassNotMatch": "Confirm Password not match",
  "photoLibLbl": "Photo Library",
  "cameraLbl": "Camera",
  "verifSentMail": "Verification email sent to ",
  "cancelLogin": "Login cancelled by the user.",
  "loginTxt": "Log In",
  "loginBtn": "Login",
  "signupBtn": "Sign Up",
  "otpVerifyLbl": "OTP Verification",
  "enterMblLbl": "Enter Your Mobile Number",
  "receiveDigitLbl":
      "You'll Receive 6 digit code for phone number verification",
  "reqOtpLbl": "Request OTP",
  "otpSentLbl": "We have sent to verification code to ",
  "resendCodeLbl": "Resend Code in",
  "mobileLbl": "Mobile",
  "darkModeLbl": "Dark Mode",
  "changeLang": "Change Language",
  "rateUs": "Rate Us",
  "shareApp": "Share App",
  "weatherLbl": "Weather Forecast",
  "categoryLbl": "Categories",
  "allLbl": "All",
  "comLbl": "Comment ",
  "saveLbl": "Save",
  "txtSizeLbl": "Text Size",
  "speakLoudLbl": "Speak Loud",
  "likeLbl": "Likes",
  "likeTxt": "like",
  "dislikeTxt": "Dislike",
  "comsLbl": "Comments",
  "shareThoghtLbl": "Share Your Thoughts.",
  "repliesLbl": "Replies",
  "publicReply": "Add a public reply...",
  "personalLbl": "Personal",
  "newsLbl": "News",
  "plzLbl": "Please",
  "fastTrendNewsLbl": "A Leap Ahead ",
  "appLogoLbl": "STARKE GLOBAL ",
  "enterOtpTxt": "Please Enter OTP",
  "otpError": "Error validating OTP, try again",
  "otpMsg": "OTP verified successfully",
  "resendLbl": "Resend OTP",
  "otpTimeoutLbl": "Otp Retrieval Timeout!!!",
  "mblRequired": "Mobile number is Required",
  "mblValid": "Please enter a valid mobile number!",
  "codeSent": "Code Sent Successfully!!!",
  "relatedNews": "You might also like",
  "optSel": "Please Select One Option!!!",
  "madeBy": "Made by",
  "skip": "Skip",
  "nxt": "Next",
  "signInTab": "Sign In",
  "agreeTermPolicyLbl": "By Logging In, you agree to our",
  "addTCFirst":
      "Please Ask Admin to Add Privacy Policy & Terms and Conditions first !!",
  "orLbl": "or Log In with",
  "signupDescr": "Create an Account",
  "signupSubDescr": "Create your account and explore more.",
  "firstAccLbl": "First to access",
  "allFunLbl": "all Functions",
  "chooseLanLbl": "Select Language",
  "videosLbl": "Videos",
  "search": "Search here...",
  "searchHomeNews": "Search News, Categories, etc.",
  "viewMore": "View More",
  "alerts": "Alerts",
  "viewFullCoverage": "View full Coverage",
  "updateName": "Update your Name",
  "loginDescr": "Let's Sign You In",
  "loginSubDescr": "Your journey starts with a secure login.",
  "logoutAcc": "Logout Account",
  "deleteAcc": "Delete Account",
  "deleteAlertTitle": "Re-Login",
  "deleteRelogin":
      "To Delete your Account, You need to Login again.\nAfter that you will be able to Delete your Account.",
  "deleteConfirm": "Are you sure?\nDo You Really Want to Delete Your Account?",
  "pwdLength": "Password should be more than 6 character long",
  "userNotFound": "No user found for given email.",
  "wrongPassword": "Wrong password provided for that user.",
  "weakPassword": "The password provided is too weak.",
  "emailAlreadyInUse": "The account already exists for that email.",
  "invalidPhoneNumber": "The provided phone number is not valid.",
  "invalidVerificationCode":
      "The sms verification code used to create the phone auth credential is invalid.",
  "ago": "ago",
  "years": "years",
  "months": "months",
  "minutes": "minutes",
  "seconds": "seconds",
  "hours": "hours",
  "days": "days",
  "justNow": "just now",
  "about": "about",
  "liveVideosLbl": "Live Videos",
  "stdPostLbl": "Standard Post",
  "videoYoutubeLbl": "Video (Youtube)",
  "videoOtherUrlLbl": "Video (Other Url)",
  "videoUploadLbl": "Video (Upload)",
  "createNewsLbl": "Create News",
  "step1Of2Lbl": "Step 1 of 2",
  "catLbl": "Category",
  "plzSelCatLbl": "Please select category",
  "subcatLbl": "SubCategory",
  "contentTypeLbl": "Content Type",
  "uploadVideoLbl": "Upload Video",
  "youtubeUrlLbl": "Youtube Url",
  "otherUrlLbl": "Other Url",
  "selContentTypeLbl": "Select Content Type",
  "titleLbl": "News Title",
  "tagLbl": "Tag",
  "addTagLbl": "Add Tag",
  "showTilledDate": "Show Till Date",
  "uploadMainImageLbl": "Upload Main Image",
  "uploadOtherImageLbl": "Upload Other Image",
  "plzUploadVideoLbl": "Please upload video!!!",
  "plzAddMainImageLbl": "Please add main image!!!",
  "selTagLbl": "Select Tag",
  "selSubCatLbl": "Select Sub Category",
  "selCatLbl": "Select Category",
  "editNewsLbl": "Edit News",
  "doYouReallyNewsLbl": "Do You Really Want to Delete this News?",
  "delNewsLbl": "Delete News",
  "newsTitleReqLbl": "News title is required!!!",
  "plzAddValidTitleLbl": "Please add valid news title!!!",
  "urlReqLbl": "Url is required!!!",
  "plzValidUrlLbl": "Please add valid url!!!",
  "manageNewsLbl": "Manage News",
  "podcastLbl": "Podcast",
  "createPodcastLbl": "Create Podcast",
  "editPodcastLbl": "Edit Podcast",
  "deletePodcastLbl": "Delete Podcast",
  "doYouReallyPodcastLbl": "Do You Really Want to Delete this Podcast?",
  "plzSelPublishDateLbl": "Please select publish date!!!",
  "podcastTitleLbl": "Podcast Title",
  "podcastDescLbl": "Podcast Description",
  "podcastTitleReqLbl": "Podcast title is required!!!",
  "podcastDescReqLbl": "Podcast description is required!!!",
  "podcastPendingApprovalMsg":
      "Your podcast has been saved successfully! It will be visible to others after admin approval.",
  "deactiveLbl": "Deactive",
  "createEpisodeLbl": "Create Episode",
  "editEpisodeLbl": "Edit Episode",
  "deleteEpisodeLbl": "Delete Episode",
  "doYouReallyEpisodeLbl": "Do You Really Want to Delete this Episode?",
  "episodeLbl": "Episode",
  "draftEpisodeLbl": "Draft Episode",
  "allEpisodeLbl": "All Episode",
  "noEpisodeLbl": "You haven't created any episode yet",
  "noDraftEpisodeLbl": "You haven't saved any episode as draft yet",
  "allPodcastLbl": "All Podcast",
  "draftPodcastLbl": "Draft Podcast",
  "episodeNoLbl": "Episode_no",
  "episodeTitleLbl": "Episode Title",
  "episodeDescLbl": "Episode Description",
  "episodeNoReqLbl": "Episode number is required!!!",
  "plzValidEpisodeNoLbl": "Please add valid episode number!!!",
  "episodeTitleReqLbl": "Episode title is required!!!",
  "episodeDescReqLbl": "Episode description is required!!!",
  "selSourceTypeLbl": "Select Source Type",
  "sourceYoutubeLbl": "YouTube Link",
  "sourceUploadLbl": "Upload Audio",
  "plzSelSourceTypeLbl": "Please select source type!!!",
  "uploadAudioLbl": "Upload Audio",
  "plzUploadAudioLbl": "Please upload audio!!!",
  "plzValidAudioFileLbl":
      "Please select a valid audio file (MP3, M4A, AAC, WAV, FLAC)!!!",
  "editLbl": "Edit",
  "noPodcastLbl": "You haven't created any podcast yet",
  "noDraftPodcastLbl": "You haven't saved any podcast as draft yet",
  "step2of2Lbl": "Step 2 of 2",
  "descLbl": "Description",
  "RetryLbl": "Retry",
  "previewLbl": "Preview",
  "sponsoredLbl": "Sponsored",
  "searchForLbl": "Search Result for",
  "readLessLbl": "Read less",
  "readMoreLbl": "Read more",
  "myProfile": "My Profile",
  "editProfile": "Edit Profile",
  "noComments": "Be the First One to Comment !!!",
  "minute": "minute",
  "read": "read",
  "selLocationLbl": "Select Location",
  "metaKeywordLbl": "Meta Keyword",
  "metaTitleLbl": "Meta Title",
  "metaDescriptionLbl": "Meta Description",
  "schemaMarkupLbl": "Schema Markup",
  "slugLbl": "Slug",
  "metaTitleWarningLbl": "Meta Title length should not exceed 60 characters.",
  "metaDescriptionWarningLbl":
      "Meta Description length should between 50 to 160 characters.",
  "metaKeywordWarningLbl":
      "Meta Keywords are not more than 10 keyword phrases & should be comma separated.",
  "slugWarningLbl":
      "Slug only accept lowercase letters, numbers, and hyphens. No spaces or special characters allowed.",
  "metaTitleRequired": "Meta title is Required",
  "metaDescriptionRequired": "Meta Description is Required",
  "metaKeywordRequired": "Meta Keyword is Required",
  "slugRequired": "Slug is Required",
  "slugValid": "Please enter valid Slug!",
  "slugUsedAlready": "This slug is already in use. Please add any other slug.",
  "maintenanceMessageLbl": "We're Under Maintenance\nPlease try again later.",
  "notificationLogin": "Please Login to view Your Notifications !!",
  "publishDate": "Publish Date",
  "dateConfirmation":
      "Please change Show till date , as it can't be set before Publish date",
  "expiredKey": "Expired News",
  "deactivatedKey": "Deactivated",
  "clearFilter": "Clear filter",
  "FilterBy": "Filter by",
  "filter": "Filter",
  "rssFeed": "FIN NEWS",
  "profile": "Profile",
  "homeLbl": "Home",
  "replyLbl": "Reply",
  "disabledCommentsMsg": "Comments are disabled for this News by admin",
  "last": "Last",
  "today": "Today",
  "clear": "Clear",
  "apply": "Apply",
  "date": "Date",
  "continueWith": "Continue with",
  "google": "Google",
  "apple": "Apple",
  "fb": "Facebook",
  "didntGetCode": "Didn't get Code?",
  "viewsLbl": "Views",
  "recentVidLbl": "Recent News Videos",
  "forceUpdateTitleLbl": "Update Required",
  "newVersionAvailableTitleLbl": "New Version Available !!!",
  "newVersionAvailableDescLbl": "Would you like to update now ?",
  "forceUpdateDescLbl":
      "A new version of this app is available with important improvements and features. To continue using the app, please update to the latest version.",
  "exitLbl": "Exit",
  "newsCreatedSuccessfully":
      "Your news has been created successfully! It will be visible to others after admin approval.",
  "summarizedDescription": "Summarized Description",
  "clickSummarizeDescription":
      "Click 'Summarize Description' to generate a summary of your content",
  "enterDescriptionFirst":
      "Add description First to generate Summarized Description",
  "authorReviewPendingLbl": "Pending Review",
  "becomeAuthorLbl": "Become an Author",
  "authorLbl": "Author",
  "saveAsDraftLbl": "Save As Draft",
  "manageNewsAllLbl": "All News",
  "manageNewsDraftLbl": "Draft News",
  "publishBtnLbl": "Publish",
  "addYourBioHintLbl": "Add your bio",
  "addLinkHereHintLbl": "Add {type} Link here",
  "noteForAuthorLbl":
      "You can add social media links & Bio only if you are the author.",
  "socialMediaLinksLbl": "Social media links",
  "followLbl": "Follow :",
  "addTagHintLbl": "Enter tag and press enter key",
  "eNewsLbl": "Skill Center",
  "eNewsNotAvailable": "Skill Center Not Available",
  "loadingPdfLbl": "Loading PDF...",
  "viewLbl": "View",
  "shareTextHeaderLbl": "Check out this news article:",
  "sharePodcastTextHeaderLbl": "Check out this Podcast:",
  "feedsLbl": "Feeds",
  "autoGenerateMetaInfo": "Auto Generate Meta Info",
  "addToShortNewsLbl": "Add to Trending",
  "reelsLbl": "NewsBuzz",
  "failedToGenerateMetaInfo": "Failed to generate meta info: No data returned",
  "metaInformationApplied": "AI-generated meta information applied"
};
